# Dockerfile.dev (Development)
FROM node:23-alpine3.20

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install -g pnpm
RUN pnpm install

# Expose API port
EXPOSE 3000

CMD ["pnpm", "run", "dev"]